### ISSUE TITLE
Product creation issue

### ISSUE THREAD

**Issue by MoGnedy** [mirumee/saleor-dashboard#379] opened 2020-01-21 14:33 UTC
### What I'm trying to achieve
I am trying to add a new product.  "/products/add"

### Steps to reproduce the problem
1. I have created a product type. e.g: "Clothing".
2. I have tried to create a new product. e.g: "Black Hoodie".
3. After the Save button is clicked, the response is a message "Saleor ran into an unexpected problem" with exception code: DoesNotExist and Message: Stock matching does not exist.
but The product is inserted in the Database and it is shown in the list but every time I try to edit it the same message appears  -> Saleor ran into an unexpected problem and the exception in the network response.

### What I expected to happen
Create a product with no errors.

### Screenshots

![01-Screen Shot 2020-01-21 at 4 12 59 PM](https://user-images.githubusercontent.com/25222631/72811997-690e5100-3c69-11ea-968e-c351c3ddce48.png)

![02-Screen Shot 2020-01-21 at 4 10 09 PM](https://user-images.githubusercontent.com/25222631/72812063-80e5d500-3c69-11ea-9b25-88d0e5066a60.png)

![03-Screen Shot 2020-01-21 at 4 11 55 PM](https://user-images.githubusercontent.com/25222631/72812103-8fcc8780-3c69-11ea-9b08-6949865eef97.png)

**System information**
Operating system:  macOS high sierra V10.13.6
Browser: Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by maarcingebala** [comment] 2020-01-22 08:51
Duplicate of #5180.

**Closed by maarcingebala** 2020-01-22 08:51 UTC
