### ISSUE TITLE
Cannot select the warehouse for product in saleor 3.0

### ISSUE THREAD

**Issue by sagital** [mirumee/saleor-dashboard#940] opened 2021-01-10 10:15 UTC
### What I'm trying to achieve
Assign a warehouse to product in order to enter stock data

### Steps to reproduce the problem
1. In the create product screen click the "+" to assign a warehouse
2. Click on the name of the warehouse to assign

### What I expected to happen
The warehouse table row should appear so I could enter the corresponding stock. Instead I am getting an error page

### Console output

```
 Uncaught TypeError: stock.data is null
    ProductStocks ProductStocks.tsx:270
```

**System information**

Operating system: 
- [ ] Windows
- [ ] Linux
- [ x] MacOS
- [ ] Other 

Browser:
- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ x] Firefox

**Comment by incorvia** [comment] 2021-01-10 22:23
I think this is a duplicate of https://github.com/mirumee/saleor-dashboard/issues/852

**Comment by sagital** [comment] 2021-01-11 06:15
No,it looks similar but it isn't. At  [#852](https://github.com/mirumee/saleor-dashboard/issues/852) you can select the warehouse and set a stock to it but it doesn't get saved. 
Here, and I think it's only for 3.0 you cannot even select the warehouse

**Comment by DTrafford** [comment] 2021-01-18 18:32
I had an issue with this.  There was error with quantityAllocated not found on null I believe.

{stock.data ? stock.data.quantityAllocated : 0}

I added this for now until there is a solution

**Comment by DTrafford** [comment] 2021-01-22 14:18
Looks like this was fixed with this: https://github.com/mirumee/saleor-dashboard/pull/954

**Closed** 2021-04-06 12:57 UTC
Labels: 3.0
